### ISSUE TITLE
Question about create_boundary

### ISSUE THREAD

**Issue by AlexTo** [TimEngelmann/ai4est#6]
Hi, first of all, thanks for the very useful repository

I'd like to have a question. What is the purpose of the `create_boundary` function?

Is it because we want to only include the minimum area that covers the trees from the GPS field data

The is the original TIF file

<img width="843" alt="image" src="https://github.com/TimEngelmann/ai4est/assets/296212/4910fd49-2ae9-477a-8781-a4c1f0843991">

And here is the image after applying the boundary

![image](https://github.com/TimEngelmann/ai4est/assets/296212/86178fbf-aaac-497b-bb6d-8d248630eb7e)

A large portion of the image has been cropped out but I'm not sure what is the main reason behind

Thanks a lot

**Comment by TimEngelmann** [comment]
Hey there, thanks for reaching out. Yes, you are right that the goal is to only consider the area where we have GPS datapoints. You can find more details about the reasoning for this in `documentation/Report_TropicalForestCarbonStockEstimation.pdf -> Section 3.1 Boundary`.

_"Only parts of these images correspond to the agro-forestry sites where field data was collected. [...] To account for this, the excess image data needs to be removed. We considered two methods to do so: using the shape files provided in the dataset and creating a boundary from the field data. The first method would be the natural choice, however, the boundaries provided are of poor quality for some sites as can be seen in Fig A.3. We thus propose creating a boundary based on the field data, for which we considered two algorithms: using their convex hull or the more complex alpha shape."_

**Comment by AlexTo** [comment]
@TimEngelmann thanks a lot, it's all clear to me now
