### ISSUE TITLE
Thank you for this work! 

### ISSUE THREAD

**Issue by daviddao** [TimEngelmann/ai4est#7]
Dear Victoria, Jan, Dimitrios & Tim,

I wanted to thank you for making this work and the code publicly available.
As a co-author of the ReforesTree paper, I would like to open this issue to let you know that we will address the problems of the dataset and keep you updated on changes.

Best,
David

**Comment by TimEngelmann** [comment]
Dear David, 
we appreciate you reaching out to us and hope our analysis and findings bring the project forward. As described in our report, we believe the GPS noise and other characteristics of the underlying data, make it a really challenging problem.
We are curious to hear your update on the progress!
